url = "http://localhost:5000"
email = "aleksey@test.com"
name = "Aleksey"
password = "qwerty1!"

btnSignUpInHomePage = "//div[@class='navbar-end']//a[contains(text(), 'Sign Up')]"
btnSignUpPath = "//div[@class='box']//button[@class='button is-block is-info is-large is-fullwidth']"
btnLogin = "//div[@class='box']//button[@class='button is-block is-info is-large is-fullwidth']"
inputEmail = "//div[@class='box']//input[@name='email']"
inputPassword = "//div[@class='box']//input[@name='password']"
inputName = "//div[@class='box']//input[@name='name']"
